# Generated by Django 2.2.7 on 2020-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191126_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
