# Generated by Django 2.2.7 on 2020-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200205_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='beginMsg',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssitem',
            name='beginTitle',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssitem',
            name='endMsg',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssitem',
            name='endTitle',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssitem',
            name='url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
