# Generated by Django 2.2.7 on 2020-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200205_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='beginMsg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='beginTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='endMsg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='endTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
