# Generated by Django 2.2.7 on 2020-04-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200205_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssitem',
            name='beginMsg',
        ),
        migrations.RemoveField(
            model_name='rssitem',
            name='beginTitle',
        ),
        migrations.RemoveField(
            model_name='rssitem',
            name='endMsg',
        ),
        migrations.RemoveField(
            model_name='rssitem',
            name='endTitle',
        ),
    ]
